// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: calculator.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Calculator {
  public static partial class Calculate
  {
    static readonly string __ServiceName = "calculator.Calculate";

    static readonly grpc::Marshaller<global::Calculator.ActionRequest> __Marshaller_ActionRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Calculator.ActionRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Calculator.ActionReply> __Marshaller_ActionReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Calculator.ActionReply.Parser.ParseFrom);

    static readonly grpc::Method<global::Calculator.ActionRequest, global::Calculator.ActionReply> __Method_GetResult = new grpc::Method<global::Calculator.ActionRequest, global::Calculator.ActionReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetResult",
        __Marshaller_ActionRequest,
        __Marshaller_ActionReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Calculator.CalculatorReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Calculate</summary>
    public abstract partial class CalculateBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Calculator.ActionReply> GetResult(global::Calculator.ActionRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Calculate</summary>
    public partial class CalculateClient : grpc::ClientBase<CalculateClient>
    {
      /// <summary>Creates a new client for Calculate</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public CalculateClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Calculate that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public CalculateClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected CalculateClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected CalculateClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Calculator.ActionReply GetResult(global::Calculator.ActionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetResult(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Calculator.ActionReply GetResult(global::Calculator.ActionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetResult, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Calculator.ActionReply> GetResultAsync(global::Calculator.ActionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetResultAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Calculator.ActionReply> GetResultAsync(global::Calculator.ActionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetResult, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override CalculateClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new CalculateClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(CalculateBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetResult, serviceImpl.GetResult).Build();
    }

  }
}
#endregion
